SystemOrganization addCategory: #ChartJs!
SystemOrganization addCategory: 'ChartJs-Component'!
SystemOrganization addCategory: 'ChartJs-Demo'!
SystemOrganization addCategory: 'ChartJs-Exception'!
SystemOrganization addCategory: 'ChartJs-Library'!
SystemOrganization addCategory: 'ChartJs-Model'!
SystemOrganization addCategory: 'ChartJs-Style'!
SystemOrganization addCategory: 'ChartJs-Types'!
