require 'open-uri'

framework_version = JSON.parse(open(url).read)

# The URL below is password protected
apps = JSON.parse(open(url).read)

app_id = Dir.pwd.split("/")[-2].to_i
app = apps[app_id.to_s]

# The app identifier is required
app_identifier "net.sunapps.#{app_id}"

version framework_version['version_number']

title(
  'de-DE' => app["fullName"]
)

description(
  'de-DE' => app["description"]["de"]
)

changelog(
  'de-DE' => framework_version["public_description"]["de"]
)

keywords(
  'de-DE' => app["keywords"]["de"].split(",")
)

app_icon "../Submission/AppIconFull.png"

price_tier 0 # free app

primary_category "Reference"

secondary_category "Business"

automatic_release true

ratings_config_path "./ratings_config.json"

app_review_information({
  first_name: "Felix",
  phone_number: "My Phone Number",
  demo_user: "",
  demo_password: "",
  notes: ""
})