require_relative "./helper"

class TestGenerated < Minitest::Test
  include Linguist

  class DataLoadedError < StandardError; end

  def error_message(blob, negate = false)
    if negate
      "#{blob} was incorrectly recognised as a generated file"
    else
      "#{blob} was not recognised as a generated file"
    end
  end

  def generated_without_loading_data(blob, negate = false)
    begin
      expected = !negate
      actual = Generated.generated?(blob, lambda { raise DataLoadedError.new })
      assert(expected == actual, error_message(blob, negate))
    rescue DataLoadedError
      assert false, "Data was loaded when calling generated? on #{blob}"
    end
  end

  def generated_loading_data(blob, negate = false)
    assert_raises(DataLoadedError, "Data wasn't loaded when calling generated? on #{blob}") do
      Generated.generated?(blob, lambda { raise DataLoadedError.new })
    end
    expected = !negate
    actual = Generated.generated?(blob, lambda { File.read(blob) })
    assert(expected == !!actual, error_message(blob, negate))
  end

  def generated_fixture_without_loading_data(name, negate = false)
    generated_without_loading_data(File.join(fixtures_path, name), negate)
  end

  def generated_fixture_loading_data(name, negate = false)
    generated_loading_data(File.join(fixtures_path, name), negate)
  end

  def generated_sample_without_loading_data(name, negate = false)
    generated_without_loading_data(File.join(samples_path, name), negate)
  end

  def generated_sample_loading_data(name, negate = false)
    generated_loading_data(File.join(samples_path, name), negate)
  end

  def test_check_generated
    # Xcode project files
    generated_sample_without_loading_data("Binary/MainMenu.nib")
    generated_sample_without_loading_data("Dummy/foo.xcworkspacedata")
    generated_sample_without_loading_data("Dummy/foo.xcuserstate")

    # Cocoapods
    generated_sample_without_loading_data("Pods/Pods.xcodeproj")
    generated_sample_without_loading_data("Pods/SwiftDependency/foo.swift")
    generated_sample_without_loading_data("Pods/ObjCDependency/foo.h")
    generated_sample_without_loading_data("Pods/ObjCDependency/foo.m")
    generated_sample_without_loading_data("Dummy/Pods/Pods.xcodeproj")
    generated_sample_without_loading_data("Dummy/Pods/SwiftDependency/foo.swift")
    generated_sample_without_loading_data("Dummy/Pods/ObjCDependency/foo.h")
    generated_sample_without_loading_data("Dummy/Pods/ObjCDependency/foo.m")

    # Carthage
    generated_sample_without_loading_data("Carthage/Build/.Dependency.version")
    generated_sample_without_loading_data("Carthage/Build/iOS/Dependency.framework")
    generated_sample_without_loading_data("Carthage/Build/Mac/Dependency.framework")
    generated_sample_without_loading_data("src/Carthage/Build/.Dependency.version")
    generated_sample_without_loading_data("src/Carthage/Build/iOS/Dependency.framework")
    generated_sample_without_loading_data("src/Carthage/Build/Mac/Dependency.framework")

    # Go-specific vendored paths
    generated_sample_without_loading_data("go/vendor/github.com/foo.go")
    generated_sample_without_loading_data("go/vendor/golang.org/src/foo.c")
    generated_sample_without_loading_data("go/vendor/gopkg.in/some/nested/path/foo.go")

    # .NET designer file
    generated_sample_without_loading_data("Dummy/foo.designer.cs")
    generated_sample_without_loading_data("Dummy/foo.Designer.cs")
    generated_sample_without_loading_data("Dummy/foo.designer.vb")
    generated_sample_without_loading_data("Dummy/foo.Designer.vb")

    # Composer generated composer.lock file
    generated_sample_without_loading_data("JSON/composer.lock")

    # Node modules
    generated_sample_without_loading_data("Dummy/node_modules/foo.js")

    # npm shrinkwrap file
    generated_sample_without_loading_data("Dummy/npm-shrinkwrap.json")
    generated_sample_without_loading_data("Dummy/package-lock.json")

    # pnpm lockfile
    generated_sample_without_loading_data("Dummy/pnpm-lock.yaml")

    # Bun lockfile
    generated_sample_without_loading_data("JSON/filenames/bun.lock")

    # Yarn Plug'n'Play file
    generated_sample_without_loading_data(".pnp.js")
    generated_sample_without_loading_data(".pnp.cjs")
    generated_sample_without_loading_data(".pnp.mjs")
    generated_sample_without_loading_data(".pnp.loader.mjs")

    # Godep saved dependencies
    generated_sample_without_loading_data("Godeps/Godeps.json")
    generated_sample_without_loading_data("Godeps/_workspace/src/github.com/kr/s3/sign.go")

    # Generated by Zephir
    generated_sample_without_loading_data("C/exception.zep.c")
    generated_sample_without_loading_data("C/exception.zep.h")
    generated_sample_without_loading_data("PHP/exception.zep.php")

    # Minified files
    generated_sample_loading_data("JavaScript/jquery-1.6.1.min.js")

    # MySQL View Definition Format (INI)
    generated_sample_loading_data("INI/metrics.frm")

    # JavaScript with source-maps
    generated_sample_loading_data("JavaScript/namespace.js")
    generated_fixture_loading_data("Generated/inline.js")

    # CSS with source-maps
    generated_fixture_loading_data("Generated/linked.css")
    generated_fixture_loading_data("Generated/inline.css")

    # Source-map
    generated_fixture_without_loading_data("Data/bootstrap.css.map")
    generated_fixture_without_loading_data("Generated/linked.css.map")
    generated_fixture_loading_data("Data/sourcemap.v3.map")
    generated_fixture_loading_data("Data/sourcemap.v1.map")

    # Specflow
    generated_fixture_without_loading_data("Features/BindingCulture.feature.cs")

    # JFlex
    generated_sample_loading_data("Java/JFlexLexer.java")

    # GrammarKit
    generated_sample_loading_data("Java/GrammarKit.java")

    # roxygen2
    generated_sample_loading_data("R/import.Rd")

    # PostScript
    generated_sample_loading_data("PostScript/lambda.pfa")

    # Perl ppport.h
    generated_fixture_loading_data("Generated/ppport.h")

    # Graphql Relay
    generated_sample_without_loading_data("Javascript/__generated__/App_user.graphql.js")

    # Game Maker Studio 2
    generated_sample_loading_data("JSON/GMS2_Project.yyp")
    generated_sample_loading_data("JSON/2ea73365-b6f1-4bd1-a454-d57a67e50684.yy")
    generated_sample_loading_data("JSON/VCT.yy")
    generated_fixture_loading_data("Generated/options_main.inherited.yy")

    # Pipenv
    generated_sample_without_loading_data("Dummy/Pipfile.lock")

    # HTML
    generated_fixture_loading_data("HTML/attr-swapped.html")
    generated_fixture_loading_data("HTML/extra-attr.html")
    generated_fixture_loading_data("HTML/extra-spaces.html")
    generated_fixture_loading_data("HTML/extra-tags.html")
    generated_fixture_loading_data("HTML/grohtml.html")
    generated_fixture_loading_data("HTML/grohtml.xhtml")
    generated_fixture_loading_data("HTML/makeinfo.html")
    generated_fixture_loading_data("HTML/mandoc.html")
    generated_fixture_loading_data("HTML/node78.html")
    generated_fixture_loading_data("HTML/org-mode.html")
    generated_fixture_loading_data("HTML/quotes-double.html")
    generated_fixture_loading_data("HTML/quotes-none.html")
    generated_fixture_loading_data("HTML/quotes-single.html")
    generated_fixture_loading_data("HTML/uppercase.html")
    generated_fixture_loading_data("HTML/ronn.html")
    generated_fixture_loading_data("HTML/unknown.html", true)
    generated_fixture_loading_data("HTML/no-content.html", true)
    generated_sample_loading_data("HTML/pages.html")

    # GIMP
    generated_fixture_loading_data("C/image.c")
    generated_fixture_loading_data("C/image.h")

    # Haxe
    generated_fixture_loading_data("Generated/Haxe/main.js")
    generated_fixture_loading_data("Generated/Haxe/main.py")
    generated_fixture_loading_data("Generated/Haxe/main.lua")
    generated_fixture_loading_data("Generated/Haxe/Main.cpp")
    generated_fixture_loading_data("Generated/Haxe/Main.h")
    generated_fixture_loading_data("Generated/Haxe/Main.java")
    generated_fixture_loading_data("Generated/Haxe/Main.cs")
    generated_fixture_loading_data("Generated/Haxe/Main.php")

    # Cargo
    generated_sample_without_loading_data("TOML/filenames/Cargo.toml.orig")

    # jOOQ
    generated_sample_loading_data("Java/generated-jooq-table.java")

    # Package.resolved
    generated_sample_without_loading_data("JSON/filenames/Package.resolved")

    # poetry
    generated_sample_without_loading_data("TOML/filenames/poetry.lock")

    # pdm
    generated_sample_without_loading_data("TOML/filenames/pdm.lock")

    # uv
    generated_sample_without_loading_data("TOML/filenames/uv.lock")

    # coverage.py `coverage html` output
    generated_sample_without_loading_data("htmlcov/index.html")
    generated_sample_without_loading_data("htmlcov/coverage_html.js")
    generated_sample_without_loading_data("htmlcov/style.css")
    generated_sample_without_loading_data("htmlcov/status.json")
    generated_sample_without_loading_data("Dummy/htmlcov/index.html")
    generated_sample_without_loading_data("Dummy/htmlcov/coverage_html.js")
    generated_sample_without_loading_data("Dummy/htmlcov/style.css")
    generated_sample_without_loading_data("Dummy/htmlcov/status.json")

    # Dart
    generated_sample_loading_data("Dart/point.dart", true)
    generated_sample_loading_data("Dart/equals.dart", true)
    generated_sample_loading_data("Dart/addressbook.pb.dart")
    generated_sample_loading_data("Dart/addressbook.pbenum.dart")
    generated_sample_loading_data("Dart/addressbook.pbjson.dart")
    generated_sample_loading_data("Dart/equals.freezed.dart")

    # Gradle Wrapper
    generated_sample_without_loading_data("Shell/filenames/gradlew")
    generated_sample_without_loading_data("Batchfile/filenames/gradlew.bat")

    # Maven Wrapper
    generated_sample_without_loading_data("Shell/filenames/mvnw")
    generated_sample_without_loading_data("Batchfile/filenames/mvnw.cmd")

    # mise-en-place lock files
    generated_sample_without_loading_data("TOML/filenames/mise.lock")
    generated_sample_without_loading_data("TOML/filenames/mise.local.lock")
    generated_sample_without_loading_data("TOML/filenames/mise.test.lock")
    generated_sample_without_loading_data("TOML/filenames/mise.test.local.lock")

    # Julia package manifests
    generated_sample_without_loading_data("TOML/filenames/Manifest.toml")
    generated_sample_without_loading_data("TOML/filenames/JuliaManifest.toml")
    generated_sample_without_loading_data("TOML/filenames/Manifest-v1.12.toml")
    generated_sample_without_loading_data("TOML/filenames/JuliaManifest-v1.12.toml")
  end

  # We've whitelisted these files on purpose, even though they're machine-generated.
  # Future contributors won't necessarily know that, so these checks are in-place to
  # catch PRs that mark these files as generated (and prevent a forgetful maintainer
  # from approving them).
  def test_check_not_generated
    # Jest snapshots (#3579)
    generated_sample_without_loading_data("Jest Snapshot/css.test.tsx.snap", true)

    # Yarn lockfiles (#4459)
    generated_sample_without_loading_data("YAML/filenames/yarn.lock", true)
  end

  def test_generated_csharp_filenames
    [
      "TemporaryGeneratedFile_AssemblyInfo.cs",
      "temporarygeneratedfile_AssemblyInfo.CS",
      "AssemblyInfo.designer.cs",
      "AssemblyInfo.Designer.CS",
      "AssemblyInfo.generated.cs",
      "AssemblyInfo.GENERATED.CS",
      "AssemblyInfo.g.cs",
      "AssemblyInfo.G.CS",
      "AssemblyInfo.g.i.cs",
      "AssemblyInfo.G.I.CS"
    ].each do |filename|
      generated_without_loading_data(File.join("src", filename))
    end
  end

  def test_generated_csharp_comments
    [
      "// <auto-generated/>\nclass C {}",
      "// <autogenerated>\nclass C {}",
      "\n \t// License\n// <auto-generated>\r\nclass C {}",
      "/* License */\n/*\n * <autogenerated>\n */\nclass C {}",
      "/// <auto-generated>\nclass C {}",
      "/** <autogenerated> */\nclass C {}",
      "\xEF\xBB\xBF// <auto-generated>\nclass C {}",
      "#nullable enable\n// <auto-generated>\nclass C {}",
      "// License\n" * 100 + "// <auto-generated>\nclass C {}",
      "/* <auto-generated"
    ].each do |content|
      assert Generated.generated?("src/Code.cs", content), content.inspect
      assert Generated.generated?("src/Code.CS", content.b), content.inspect
    end
  end

  def test_non_generated_csharp
    [
      "",
      "class C {}",
      "// <Auto-Generated>\nclass C {}",
      "// auto-generated\nclass C {}",
      "class C {}\n// <auto-generated>",
      "/* License */ class C {} // <autogenerated>",
      'class C { string s = "<auto-generated>"; }',
      '[System.CodeDom.Compiler.GeneratedCode("tool", "1")] class C {}',
      "#region <auto-generated>\nclass C {}",
      "#if false\n// <auto-generated>\n#endif\nclass C {}",
      "# if DEBUG\n/* <autogenerated> */\n#endif\nclass C {}"
    ].each do |content|
      refute Generated.generated?("src/Code.cs", content), content.inspect
    end

    [
      "src/Code.generated.csx",
      "src/Code.g.i.cs.txt",
      "src/NotTemporaryGeneratedFile_Code.cs",
      "src/TemporaryGeneratedFile_/Code.cs",
      "src/Code.generated.cs/Code.cs",
      "src/Codegenerated.cs",
      "src/Code.gi.cs"
    ].each do |filename|
      refute Generated.generated?(filename, ""), filename
    end

    refute Generated.generated?("src/Code.js", "// <auto-generated>\nclass C {}")
  end

  def test_generated_vb_filenames
    [
      "TemporaryGeneratedFile_AssemblyInfo.vb",
      "temporarygeneratedfile_AssemblyInfo.VB",
      "AssemblyInfo.designer.vb",
      "AssemblyInfo.Designer.VB",
      "AssemblyInfo.generated.vb",
      "AssemblyInfo.GENERATED.VB",
      "AssemblyInfo.g.vb",
      "AssemblyInfo.G.VB",
      "AssemblyInfo.g.i.vb",
      "AssemblyInfo.G.I.VB"
    ].each do |filename|
      generated_without_loading_data(File.join("src", filename))
    end
  end

  def test_generated_vb_comments
    [
      "' <auto-generated/>\nClass C\nEnd Class",
      "' <autogenerated>\nClass C\nEnd Class",
      "\n \t' License\n' <auto-generated>\r\nClass C\nEnd Class",
      "''' <auto-generated>\nClass C\nEnd Class",
      "REM <auto-generated>\nClass C\nEnd Class",
      "rem <autogenerated>\nClass C\nEnd Class",
      "ReM\t<auto-generated>\nClass C\nEnd Class",
      "\xEF\xBB\xBF' <auto-generated>\nClass C\nEnd Class",
      "#Region \"Code\"\n' <auto-generated>\nClass C\nEnd Class",
      "' License\n" * 100 + "' <auto-generated>\nClass C\nEnd Class"
    ].each do |content|
      assert Generated.generated?("src/Code.vb", content), content.inspect
      assert Generated.generated?("src/Code.VB", content.b), content.inspect
    end
  end

  def test_non_generated_vb
    [
      "",
      "Class C\nEnd Class",
      "' <Auto-Generated>\nClass C\nEnd Class",
      "' auto-generated\nClass C\nEnd Class",
      "Class C\nEnd Class\n' <auto-generated>",
      "Dim s As String = \"<auto-generated>\"",
      "Remember = \"<auto-generated>\"",
      "<System.CodeDom.Compiler.GeneratedCode(\"tool\", \"1\")> Class C\nEnd Class",
      "#Region \"<auto-generated>\"\nClass C\nEnd Class",
      "#If False Then\n' <auto-generated>\n#End If\nClass C\nEnd Class",
      "# If DEBUG Then\nREM <autogenerated>\n#End If\nClass C\nEnd Class",
      "// <auto-generated>\nClass C\nEnd Class",
      "/* <auto-generated> */\nClass C\nEnd Class"
    ].each do |content|
      refute Generated.generated?("src/Code.vb", content), content.inspect
    end

    [
      "src/Code.generated.vbx",
      "src/Code.g.i.vb.txt",
      "src/NotTemporaryGeneratedFile_Code.vb",
      "src/TemporaryGeneratedFile_/Code.vb",
      "src/Code.generated.vb/Code.vb",
      "src/Codegenerated.vb",
      "src/Code.gi.vb"
    ].each do |filename|
      refute Generated.generated?(filename, ""), filename
    end

    refute Generated.generated?("src/Code.cs", "' <auto-generated>\nclass C {}")
    refute Generated.generated?("src/Code.cs", "REM <auto-generated>\nclass C {}")
  end
end
