require_relative "./helper"

class TestGenerated < Test::Unit::TestCase
  include Linguist

  def samples_path
    File.expand_path("../../samples", __FILE__)
  end

  def generated_without_loading_data?(name)
    blob = File.join(samples_path, name)
    Generated.generated?(blob, lambda { "" })
  end

  def check_generated_without_loading_data(name)
    assert generated_without_loading_data?(name), "Data was loaded when calling generated? on #{name}"
  end

  def test_check_generated_without_loading_data
    # Xcode project files
    check_generated_without_loading_data("Binary/MainMenu.nib")
    check_generated_without_loading_data("Dummy/foo.xcworkspacedata")
    check_generated_without_loading_data("Dummy/foo.xcuserstate")

    # .NET designer file
    check_generated_without_loading_data("Dummu/foo.designer.cs")

    # Composer generated composer.lock file
    check_generated_without_loading_data("JSON/composer.lock")

    # Node modules
    check_generated_without_loading_data("Dummy/node_modules/foo.js")

    # Godep saved dependencies
    check_generated_without_loading_data("Godeps/Godeps.json")
    check_generated_without_loading_data("Godeps/_workspace/src/github.com/kr/s3/sign.go")

    # Generated by Zephir
    check_generated_without_loading_data("Zephir/filenames/exception.zep.c")
    check_generated_without_loading_data("Zephir/filenames/exception.zep.h")
    check_generated_without_loading_data("Zephir/filenames/exception.zep.php")

    # Minified files
    assert !generated_without_loading_data?("JavaScript/jquery-1.6.1.min.js"), "Data wasn't loaded when calling generated? on JavaScript/jquery-1.6.1.min.js"
  end
end
