require_relative "./helper"

require "digest"
require "set"

# Validates that languages introduced by the change under review carry a
# `language_id` generated by `script/update-ids`.
#
# We deliberately only check *new* languages. Existing languages predate the
# current generator and keep their original (often sequential) IDs, and a
# rename reuses the original language_id so GitHub keeps tracking the language.
# Validating either of those would produce noise, so we diff languages.yml
# against the point this branch diverged from the default branch and ignore
# anything that isn't a brand-new entry.
class TestLanguageId < Minitest::Test
  ROOT = File.expand_path("..", __dir__)
  LANGUAGES_PATH = File.join(ROOT, "lib", "linguist", "languages.yml")
  BASE_REFS = %w[main origin/main].freeze

  def test_new_language_ids_are_generated_by_the_script
    base = base_languages
    skip "Could not resolve a base revision to diff languages.yml against" if base.nil?

    current = YAML.load(File.read(LANGUAGES_PATH))
    known_ids = base.values.map { |language| language["language_id"] }.compact.to_set

    (current.keys - base.keys).each do |name|
      language_id = current[name]["language_id"]

      # A new entry that reuses an existing ID is a rename, not a new language.
      next if known_ids.include?(language_id)

      expected = generate_language_id(name)
      assert_equal expected, language_id, <<~MSG
        Language '#{name}' has an incorrect language_id (expected #{expected}, got #{language_id.inspect}).
        Run `script/update-ids` to generate it.
      MSG
    end
  end

  private

  # Mirrors the generator in script/update-ids.
  def generate_language_id(name)
    Digest::SHA256.hexdigest(name).to_i(16) % (2**30 - 1)
  end

  # languages.yml as it existed where this branch diverged from the default
  # branch, or nil when that point can't be resolved (e.g. a shallow clone or a
  # checkout without the default branch), in which case the test is skipped.
  def base_languages
    BASE_REFS.each do |ref|
      base = git("merge-base", "HEAD", ref)
      next if base.nil?

      content = git("show", "#{base.strip}:lib/linguist/languages.yml")
      return YAML.load(content) unless content.nil?
    end
    nil
  end

  def git(*args)
    output = IO.popen(["git", "-C", ROOT, *args], err: File::NULL, &:read)
    $?.success? ? output : nil
  end
end
