version: 2
updates:
  # Check for Ruby gem updates
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
  # Check for GitHub Actions updates
  - package-ecosystem: "github-actions"
    # Look for GitHub Actions workflows in the `root` directory
    directory: "/"
    # Check the for updates once a week
    schedule:
      interval: "weekly"
