---
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/script/regex-compatibility/rust"
    schedule:
      interval: "daily"
