version: 2
updates:
  # Only check for Ruby gem updates
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
     interval: daily
  
