version: 2
updates:
  # Only check for Ruby gem updates
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
  # Ignore /samples
  - package-ecosystem: "bundler"
    directory: "/samples"
    schedule:
      interval: "monthly"
    ignore:
    - dependency-name: "*"
  - package-ecosystem: "maven"
    directory: "/samples"
    schedule:
      interval: "monthly"
    ignore:
    - dependency-name: "*"
  - package-ecosystem: "cargo"
    directory: "/samples"
    schedule:
      interval: "monthly"
    ignore:
    - dependency-name: "*"
  - package-ecosystem: "pip"
    directory: "/samples"
    schedule:
      interval: "monthly"
    ignore:
    - dependency-name: "*"
  - package-ecosystem: "composer"
    directory: "/samples"
    schedule:
      interval: "monthly"
    ignore:
    - dependency-name: "*"
  - package-ecosystem: "bundler"
    directory: "/samples"
    schedule:
      interval: "monthly"
    ignore:
    - dependency-name: "*"
