<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" charset="UTF-8" type="text/css" href="main.css">
<meta charset="UTF-8">
</head>
<body>
    <div id="panel_header_main_form">
        <p id="panel_header_main_form_title">Поддержка:</p>
    </div>
    <table>
        <tbody>
            <tr>
                <td>    
                    <p>Москва:</p>
                </td>
                <td>    
                    <p>+7-902-7-800-807</p>
                </td>
            </tr>
            <tr>
                <td>    
                    <p>Регионы:</p>
                </td>
                <td>    
                    <p>+7-902-7-800-807</p>
                </td>
            </tr>
        </tbody>
    </table>
</body>
