blank_issues_enabled: false
contact_links:
  - name: Get help in GitHub Discussions
    url: https://github.com/github/linguist/discussions
    about: Have a question? Surprised by your repository language analysis? The quickest way to get help is on Linguist's GitHub Discussions!
