#!/bin/sh

displayUsage()
{
    echo "---------------------------------------------------------------------------"
    echo "Build container: "
    echo "  docker-cli build"
    echo ""
    echo "Start container: "
    echo "  docker-cli start"
    echo ""
    echo "Stop container: "
    echo "  docker-cli stop"
    echo ""
    echo "Connect to dev container: "
    echo "  docker-cli exec"
    echo "---------------------------------------------------------------------------"
}


start()
{
    docker-compose -f docker/docker-compose.yml up --build -d
}

stop()
{
    docker-compose -f docker/docker-compose.yml down
}

build()
{
    docker-compose -f docker/docker-compose.yml build
}

containerExec()
{
    docker-compose -f docker/docker-compose.yml exec linguist bash
}

case "$1" in
    build)
        build
    ;;
    start)
        start
    ;;
    stop)
        stop
    ;;
    exec)
        containerExec
    ;;
    *) displayUsage
    ;;
esac