
#line 3 "lex.linguist_yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define linguist_yy_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer linguist_yy_create_buffer
#endif

#ifdef yy_delete_buffer
#define linguist_yy_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer linguist_yy_delete_buffer
#endif

#ifdef yy_scan_buffer
#define linguist_yy_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer linguist_yy_scan_buffer
#endif

#ifdef yy_scan_string
#define linguist_yy_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string linguist_yy_scan_string
#endif

#ifdef yy_scan_bytes
#define linguist_yy_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes linguist_yy_scan_bytes
#endif

#ifdef yy_init_buffer
#define linguist_yy_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer linguist_yy_init_buffer
#endif

#ifdef yy_flush_buffer
#define linguist_yy_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer linguist_yy_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define linguist_yy_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state linguist_yy_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define linguist_yy_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer linguist_yy_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define linguist_yypush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state linguist_yypush_buffer_state
#endif

#ifdef yypop_buffer_state
#define linguist_yypop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state linguist_yypop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define linguist_yyensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack linguist_yyensure_buffer_stack
#endif

#ifdef yylex
#define linguist_yylex_ALREADY_DEFINED
#else
#define yylex linguist_yylex
#endif

#ifdef yyrestart
#define linguist_yyrestart_ALREADY_DEFINED
#else
#define yyrestart linguist_yyrestart
#endif

#ifdef yylex_init
#define linguist_yylex_init_ALREADY_DEFINED
#else
#define yylex_init linguist_yylex_init
#endif

#ifdef yylex_init_extra
#define linguist_yylex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra linguist_yylex_init_extra
#endif

#ifdef yylex_destroy
#define linguist_yylex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy linguist_yylex_destroy
#endif

#ifdef yyget_debug
#define linguist_yyget_debug_ALREADY_DEFINED
#else
#define yyget_debug linguist_yyget_debug
#endif

#ifdef yyset_debug
#define linguist_yyset_debug_ALREADY_DEFINED
#else
#define yyset_debug linguist_yyset_debug
#endif

#ifdef yyget_extra
#define linguist_yyget_extra_ALREADY_DEFINED
#else
#define yyget_extra linguist_yyget_extra
#endif

#ifdef yyset_extra
#define linguist_yyset_extra_ALREADY_DEFINED
#else
#define yyset_extra linguist_yyset_extra
#endif

#ifdef yyget_in
#define linguist_yyget_in_ALREADY_DEFINED
#else
#define yyget_in linguist_yyget_in
#endif

#ifdef yyset_in
#define linguist_yyset_in_ALREADY_DEFINED
#else
#define yyset_in linguist_yyset_in
#endif

#ifdef yyget_out
#define linguist_yyget_out_ALREADY_DEFINED
#else
#define yyget_out linguist_yyget_out
#endif

#ifdef yyset_out
#define linguist_yyset_out_ALREADY_DEFINED
#else
#define yyset_out linguist_yyset_out
#endif

#ifdef yyget_leng
#define linguist_yyget_leng_ALREADY_DEFINED
#else
#define yyget_leng linguist_yyget_leng
#endif

#ifdef yyget_text
#define linguist_yyget_text_ALREADY_DEFINED
#else
#define yyget_text linguist_yyget_text
#endif

#ifdef yyget_lineno
#define linguist_yyget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno linguist_yyget_lineno
#endif

#ifdef yyset_lineno
#define linguist_yyset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno linguist_yyset_lineno
#endif

#ifdef yyget_column
#define linguist_yyget_column_ALREADY_DEFINED
#else
#define yyget_column linguist_yyget_column
#endif

#ifdef yyset_column
#define linguist_yyset_column_ALREADY_DEFINED
#else
#define yyset_column linguist_yyset_column
#endif

#ifdef yywrap
#define linguist_yywrap_ALREADY_DEFINED
#else
#define yywrap linguist_yywrap
#endif

#ifdef yyalloc
#define linguist_yyalloc_ALREADY_DEFINED
#else
#define yyalloc linguist_yyalloc
#endif

#ifdef yyrealloc
#define linguist_yyrealloc_ALREADY_DEFINED
#else
#define yyrealloc linguist_yyrealloc
#endif

#ifdef yyfree
#define linguist_yyfree_ALREADY_DEFINED
#else
#define yyfree linguist_yyfree
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[255] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   80,   78,   60,   32,
       61,   62,   63,   64,   33,   39,   39,   65,   66,   67,
       59,   68,   52,   34,   34,   69,   70,   52,   49,   52,
       71,   72,   35,   41,   73,   41,   74,   75,   40,   76,
       40,   77,   78,   32,   61,   62,   63,   33,   59,   68,
       52,   70,   23,   23,   23,   23,   23,   23,   23,   23,
       60,   48,   51,   54,   31,   61,   35,   62,   42,    0,
       42,   63,   53,   64,   44,   45,   31,   39,   36,   19,
        0,    0,   39,   65,   66,   67,   59,   46,   56,   57,

       68,   16,   52,   34,   34,   35,   34,   34,   35,   55,
       69,   70,   50,   50,   44,   47,   52,   52,   49,   52,
       49,   44,   71,   72,    0,   41,   38,   73,   41,   74,
       75,   18,    0,   40,   37,   76,   40,   77,    0,    0,
        0,    0,    0,    0,    0,    8,    8,    3,    3,    0,
       61,    0,    7,    7,   63,    0,    0,   59,    0,    0,
       35,    5,    9,    9,   70,   24,    0,   26,   27,    0,
        0,    0,   20,   42,   21,    0,   58,   56,   57,   15,
       14,    0,   34,   34,   34,   34,   34,    0,    0,    0,
        0,    5,    8,    3,    0,    2,    0,    2,    2,   12,

        7,   11,    6,    6,   10,   35,    5,    5,    5,    5,
        9,   25,   28,   29,   30,    0,   13,   34,   34,   34,
       34,   34,   34,   34,   17,    0,    0,    0,    2,   12,
       12,   11,   11,    6,   10,   10,   22,    4,    4,   43,
       34,   34,   34,    0,    2,    4,    0,    0,    0,    0,
        0,    1,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   29,   29,   29,   30,   31,
       32,   32,   32,   32,   32,   33,   32,   32,   32,   32,
       32,   32,   32,   32,   34,   32,   32,   32,   32,   32,
       35,   36,   37,   38,   32,   39,   29,   29,   29,   29,

       40,   31,   41,   32,   42,   32,   32,   33,   32,   43,
       32,   32,   32,   32,   32,   32,   34,   44,   32,   45,
       32,   32,   46,   47,   48,   49,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    2,    3,    2,    4,    1,    5,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    6,    7,
        7,    1,    1,    4,    1,    4,    4,    4,    7,    7,
        7,    7,    7,    7,    1,    1,    1,    1,    1,    7,
        7,    7,    7,    7,    7,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[272] =
    {   0,
        0,   48,  598,  597,  593,  592,  591,  590,  592,  591,
      566,  543,  524,  519,  511,  510,  522,  613,   48,  509,
      501,   56,   51,   59,  482,   68,  479,   37,   63,  475,
       73,   86,   89,   98,  445,   95,  466,  139,   85,  126,
       95,   51,  475,   52,  445,  443,   58,  439,  107,  137,
      429,  108,  183,  165,  169,  471,  179,  175,  182,  176,
      195,  190,  613,  456,  457,  425,  459,  465,  459,  451,
       67,  443,  613,  613,  461,  459,  458,  456,  451,  425,
      415,  451,  434,  447,  423,  613,  437,  147,  434,  613,
      428,  423,  425,  423,  421,  418,  109,  407,   80,  176,

      414,  156,  191,  204,  386,  216,  209,  168,  225,  613,
      408,  406,  411,  613,  410,  409,  217,  233,  171,  242,
      202,  613,  398,  396,  405,  192,  385,  385,  383,  381,
      379,  613,  399,  201,  368,  368,  365,  361,    0,  259,
      266,  268,  392,  389,  271,  613,    0,  613,    0,  276,
      278,  403,  613,    0,  280,  284,  400,  287,  296,  397,
      223,  298,  613,    0,  289,  613,  373,  613,  613,  392,
      386,  391,  613,  353,  613,  369,  613,  613,  613,  613,
      367,  236,  274,  352,  288,  269,  315,  367,  365,  355,
      307,  320,    0,    0,  348,  324,  324,  325,  299,  331,

        0,  312,  613,    0,  303,  311,  296,  613,  327,  351,
        0,  613,  613,  613,  613,  274,  613,  246,  320,  241,
      371,    0,  322,    0,  613,  161,  133,  220,  110,  134,
      613,  120,  613,    0,  102,  613,  613,  613,   72,  613,
      613,  346,    0,  319,  362,   58,  352,  410,  374,  370,
      377,  454,  378,  613,  499,  502,  506,  512,  519,  525,
      532,  539,  546,  548,  555,  562,  569,  576,  583,  590,
      597
    } ;

static const flex_int16_t yy_def[272] =
    {   0,
      254,    1,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  254,  254,  254,  254,
      256,  256,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  256,  254,  254,   34,  254,  254,  254,  254,  254,
      254,  256,  256,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  256,   22,  254,  254,  254,   32,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  256,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,

      254,  254,  254,  254,   34,  256,  256,  256,  256,  254,
      254,  254,  254,  254,  254,  254,  257,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,   53,  254,
      254,  254,  254,  254,  254,  254,  258,  254,  259,  260,
      254,  254,  254,  261,  254,  254,  254,  254,  254,  254,
      256,  262,  254,  263,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  256,  254,  254,  254,  254,
      254,  262,  258,  259,  260,  195,  264,  195,  198,  265,

      261,  266,  254,  267,  268,  256,  262,  254,  262,  262,
      263,  254,  254,  254,  254,  254,  254,  254,  254,  256,
      254,  187,  187,  187,  254,  254,  254,  264,  198,  265,
      254,  266,  254,  267,  268,  254,  254,  254,  269,  254,
      254,  221,  221,  264,  198,  269,  264,  270,  264,  270,
      271,  270,  271,    0,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254
    } ;

static const flex_int16_t yy_nxt[663] =
    {   0,
       18,   18,   18,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   43,
       43,   43,   43,   43,   44,   45,   46,   47,   48,   43,
       43,   43,   43,   43,   43,   49,   50,   51,   52,   53,
       94,   53,   71,   54,   55,   56,   57,  254,   58,   82,
      208,   83,  254,   78,   59,   60,   61,   79,   84,  125,
       62,   71,   72,   73,  208,   83,   73,   95,  124,   88,
       89,   90,   83,   83,   85,   91,  126,   83,  127,   97,
       80,   72,  254,   99,   92,  130,   74,   83,   98,   99,

      100,   81,  102,  101,  254,   86,  178,  103,  121,  119,
      121,  110,  103,   83,  103,  104,  111,  105,  105,   83,
       73,  123,  254,  132,  133,   97,   77,  106,  107,   77,
      107,  108,   83,   74,   98,  122,  254,  106,   77,   77,
       77,   77,  109,  113,  103,  114,   86,  114,  115,  120,
      119,  120,  134,  245,  135,  116,  138,  117,   88,   89,
      180,   83,  118,  119,  120,  114,  114,  146,  147,  181,
       75,  148,  149,  150,  254,  151,  156,  159,  156,  159,
      240,  153,  154,  136,  139,   87,  139,  155,  140,  141,
      100,  142,  163,  164,  121,  119,  121,  240,  158,  143,

      186,  144,  179,   83,   73,  145,   83,   98,  102,  103,
      157,  160,  165,  162,  103,  254,  103,  161,  103,   83,
      103,  104,  254,  104,  104,  121,  126,  121,  127,  254,
      185,  254,  185,  182,  183,  103,  183,  184,  228,  107,
      103,  107,  103,  182,  187,  187,  134,  254,  135,  116,
      185,  103,  185,  187,  187,  187,  118,  119,  120,  244,
      103,  146,  147,  206,  187,  120,  119,  120,  148,  149,
      153,  154,  141,  163,  164,  254,  142,  195,  241,  195,
      148,  149,  153,  154,  151,  156,  240,  156,  155,  203,
      204,  163,  164,  145,  196,  197,  197,  159,  208,  159,

      208,  220,  209,   97,  183,  236,  183,  219,  219,  203,
      204,  165,   98,  237,  233,  199,  210,  254,  183,  157,
      183,  210,  208,  210,  209,  254,  254,  254,  254,  238,
      239,  160,  221,  231,  222,  222,  185,  228,  185,  219,
      219,  229,  228,  222,  223,  224,   77,  107,  108,  195,
      183,  195,  183,  208,  223,   77,   77,   77,   77,   77,
      185,  247,  185,  248,  198,  248,  196,  197,  197,  210,
      228,  254,  227,  254,  210,  248,  210,  248,  248,  248,
      248,  248,  226,  225,  218,  217,  216,  199,  221,  174,
      221,  221,  228,  215,  251,  249,  214,  213,  212,  221,

      242,  243,  205,  183,  184,  202,  200,  192,  191,  138,
      242,  248,  137,  248,  136,  135,  190,  131,  130,  129,
      128,  127,  189,  124,  123,  116,  122,  188,  112,  111,
       77,  101,   98,   96,  251,   95,   94,   93,  252,  252,
      252,  252,  252,  252,  177,  176,   89,  175,  122,  252,
      252,  252,  252,  252,  252,  254,   84,  254,   83,   82,
       81,  174,   79,   78,  254,   76,  173,   72,  172,  171,
      170,  169,  168,  167,  166,  152,  137,  131,  251,  129,
      128,  254,  252,  252,  252,  252,  252,  252,  112,   77,
       96,   93,   87,  252,  252,  252,  252,  252,  252,   63,

       63,   63,   63,   63,   63,   63,   77,   76,   77,  114,
      114,  114,  193,  193,   75,  193,  193,  193,  193,  194,
      194,  254,  194,  194,  194,  194,  198,   70,   70,   69,
      198,  198,  201,  201,   69,  201,  201,  201,  201,  207,
      207,  207,  207,  207,  207,  207,  211,  211,   68,  211,
      211,  211,  211,  197,  197,  230,  230,  230,  230,  230,
      230,  230,  232,  232,  232,  232,  232,  232,  232,  234,
      234,   68,  234,  234,  234,  234,  235,  235,  235,  235,
      235,  235,  235,  246,  246,  246,  246,  246,  246,  246,
      250,  250,  250,  250,  250,  250,  250,  253,  253,  253,

      253,  253,  253,  253,   67,   67,   66,   66,   65,   65,
       64,   64,   17,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254
    } ;

static const flex_int16_t yy_chk[663] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
       28,    2,   19,    2,    2,    2,    2,   42,    2,   23,
      246,   28,   22,   22,    2,    2,    2,   22,   24,   44,
        2,   71,   19,   19,  239,   23,   23,   29,   42,   26,
       26,   26,   47,   24,   24,   26,   44,   29,   44,   31,
       22,   71,   32,   99,   26,   47,   19,   31,   31,   32,

       32,   22,   33,   32,  235,   24,   99,   33,   39,   39,
       39,   36,   33,   33,   33,   34,   36,   34,   34,   36,
       41,   41,  232,   49,   49,   97,   34,   34,   34,   34,
       34,   34,   52,   39,   97,   40,  230,   34,   34,   34,
       34,   34,   34,   38,   40,   38,   50,   38,   38,   40,
       40,   40,   49,  229,   49,   38,   52,   38,   88,   88,
      102,   50,   38,   38,   38,   38,   38,   54,   54,  102,
       54,   55,   55,   55,  108,   55,   58,   60,   58,   60,
      227,   57,   57,   50,   53,   58,   53,   57,   53,   53,
      100,   53,   62,   62,  119,  119,  119,  226,   59,   53,

      108,   53,  100,   57,   57,   53,   59,   59,   61,  103,
       58,   60,   62,   61,  103,  107,  103,   60,   61,   61,
       61,  104,  106,  104,  104,  121,  126,  121,  126,  161,
      106,  109,  106,  104,  104,  117,  104,  104,  228,  107,
      117,  107,  117,  104,  109,  109,  134,  220,  134,  118,
      182,  118,  182,  109,  109,  109,  118,  118,  118,  228,
      120,  140,  140,  161,  109,  120,  120,  120,  141,  141,
      142,  142,  141,  145,  145,  186,  142,  150,  218,  150,
      151,  151,  155,  155,  151,  156,  216,  156,  155,  158,
      158,  165,  165,  145,  150,  150,  150,  159,  207,  159,

      162,  186,  162,  158,  183,  205,  183,  185,  185,  191,
      191,  165,  158,  206,  202,  150,  162,  206,  185,  156,
      185,  162,  192,  162,  192,  196,  198,  196,  198,  209,
      209,  159,  187,  200,  187,  187,  223,  244,  223,  219,
      219,  199,  197,  187,  187,  187,  187,  187,  187,  195,
      219,  195,  219,  210,  187,  187,  187,  187,  187,  187,
      242,  244,  242,  245,  198,  245,  195,  195,  195,  210,
      247,  250,  190,  250,  210,  249,  210,  249,  251,  253,
      251,  253,  189,  188,  184,  181,  176,  195,  221,  174,
      221,  221,  249,  172,  250,  247,  171,  170,  167,  221,

      221,  221,  160,  221,  221,  157,  152,  144,  143,  138,
      221,  248,  137,  248,  136,  135,  133,  131,  130,  129,
      128,  127,  125,  124,  123,  116,  115,  113,  112,  111,
      105,  101,   98,   96,  248,   95,   94,   93,  248,  248,
      248,  248,  248,  248,   92,   91,   89,   87,   85,  248,
      248,  248,  248,  248,  248,  252,   84,  252,   83,   82,
       81,   80,   79,   78,   77,   76,   75,   72,   70,   69,
       68,   67,   66,   65,   64,   56,   51,   48,  252,   46,
       45,   43,  252,  252,  252,  252,  252,  252,   37,   35,
       30,   27,   25,  252,  252,  252,  252,  252,  252,  255,

      255,  255,  255,  255,  255,  255,  256,   21,  256,  257,
      257,  257,  258,  258,   20,  258,  258,  258,  258,  259,
      259,   17,  259,  259,  259,  259,  260,   16,   15,   14,
      260,  260,  261,  261,   13,  261,  261,  261,  261,  262,
      262,  262,  262,  262,  262,  262,  263,  263,   12,  263,
      263,  263,  263,  264,  264,  265,  265,  265,  265,  265,
      265,  265,  266,  266,  266,  266,  266,  266,  266,  267,
      267,   11,  267,  267,  267,  267,  268,  268,  268,  268,
      268,  268,  268,  269,  269,  269,  269,  269,  269,  269,
      270,  270,  270,  270,  270,  270,  270,  271,  271,  271,

      271,  271,  271,  271,   10,    9,    8,    7,    6,    5,
        4,    3,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "tokenizer.l"
#line 2 "tokenizer.l"

#include "ruby.h"

// Anything longer is unlikely to be useful.
#define MAX_TOKEN_LEN 16

#define FEED2(s, l) do { \
    const char* __s = (s); \
    const size_t __l = (l); \
    const size_t __cl = __l > MAX_TOKEN_LEN? MAX_TOKEN_LEN : __l; \
    *yyextra = rb_str_new(__s, __cl); \
  } while(0)

#define FEED1(s) FEED2(s, strlen(s))

#define FEED() FEED2(yytext, yyleng)

#define FEED_STATIC(s) FEED2(s, sizeof(s) - 1)

#define FEED_SHEBANG(s) do { \
    const size_t __l = strlen(s); \
    const size_t __cl = __l > MAX_TOKEN_LEN? MAX_TOKEN_LEN : __l; \
    *yyextra = rb_str_new("SHEBANG#!", sizeof("SHEBANG#!") - 1); \
    rb_str_cat(*yyextra, s, __cl); \
  } while(0)

#define eat_until_eol() do { \
    int c; \
    while ((c = input(yyscanner)) != '\n' && c != EOF && c); \
    if (c == EOF || !c) \
      return 0; \
  } while (0)

#define eat_until_unescaped(q) do { \
    int c; \
    while ((c = input(yyscanner)) != EOF && c) { \
      if (c == '\n') \
        break; \
      if (c == '\\') { \
        c = input(yyscanner); \
        if (c == EOF || !c) \
          return 0; \
      } else if (c == q) \
        break; \
    } \
    if (c == EOF || !c) \
      return 0; \
  } while (0)

#line 911 "lex.linguist_yy.c"

#line 913 "lex.linguist_yy.c"

#define INITIAL 0
#define c_comment 1
#define xml_comment 2
#define haskell_comment 3
#define ocaml_comment 4
#define python_dcomment 5
#define python_scomment 6
#define roff_comment 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE VALUE*

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT

#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 56 "tokenizer.l"


#line 1182 "lex.linguist_yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 255 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 254 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 58 "tokenizer.l"
{
  const char *off = strrchr(yytext, ' ');
  if (!off)
    off = yytext;
  else
    ++off;
  FEED_SHEBANG(off);
  eat_until_eol();
  return 1;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 69 "tokenizer.l"
{
  const char *off = strrchr(yytext, '/');
  if (!off)
    off = yytext;
  else
   ++off;
  if (strcmp(off, "env") == 0) {
    eat_until_eol();
  } else {
    FEED_SHEBANG(off);
    eat_until_eol();
    return 1;
  }
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 84 "tokenizer.l"
{ FEED_STATIC("COMMENT#"); return 1; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 85 "tokenizer.l"
{ FEED_STATIC("COMMENT//!"); return 1; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 86 "tokenizer.l"
{ FEED_STATIC("COMMENT//"); return 1; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 87 "tokenizer.l"
{ FEED_STATIC("COMMENT--"); return 1; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 88 "tokenizer.l"
{ FEED_STATIC("COMMENT%"); return 1; }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 89 "tokenizer.l"
{ FEED_STATIC("COMMENT\""); return 1; }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 90 "tokenizer.l"
{ FEED_STATIC("COMMENT;"); return 1; }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 91 "tokenizer.l"
{ FEED_STATIC("COMMENT.\\\""); return 1; }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 92 "tokenizer.l"
{ FEED_STATIC("COMMENT'\\\""); return 1; }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 93 "tokenizer.l"
{ FEED_STATIC("COMMENT$!"); return 1; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 95 "tokenizer.l"
{ FEED_STATIC("COMMENT/*"); return 1; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 96 "tokenizer.l"
{ FEED_STATIC("COMMENT/**"); BEGIN(c_comment); return 1; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 97 "tokenizer.l"
{ FEED_STATIC("COMMENT/*!"); BEGIN(c_comment); return 1; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 98 "tokenizer.l"
{ FEED_STATIC("COMMENT/*"); BEGIN(c_comment); return 1; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 99 "tokenizer.l"
{ FEED_STATIC("COMMENT<!--"); BEGIN(xml_comment); return 1; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 100 "tokenizer.l"
{ FEED_STATIC("COMMENT{-"); BEGIN(haskell_comment); return 1; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 101 "tokenizer.l"
{ FEED_STATIC("COMMENT(*"); BEGIN(ocaml_comment); return 1; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 102 "tokenizer.l"
{ FEED_STATIC("COMMENT\"\"\""); BEGIN(python_dcomment); return 1; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 103 "tokenizer.l"
{ FEED_STATIC("COMMENT'''"); BEGIN(python_scomment); return 1; }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 104 "tokenizer.l"
{ FEED_STATIC("COMMENT.ig"); BEGIN(roff_comment); return 1; }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 106 "tokenizer.l"
{ /* nothing */ }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 107 "tokenizer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 108 "tokenizer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 109 "tokenizer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 110 "tokenizer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 111 "tokenizer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 112 "tokenizer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 113 "tokenizer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 115 "tokenizer.l"
{ /* nothing */ }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 116 "tokenizer.l"
{ eat_until_unescaped('"'); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 117 "tokenizer.l"
{ eat_until_unescaped('\''); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 118 "tokenizer.l"
{ /* nothing */ }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 120 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 122 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 123 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 124 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 125 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 126 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 127 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 128 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 130 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 132 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 133 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 135 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 136 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 138 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 139 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 140 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 141 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 142 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 143 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 144 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 145 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 147 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 148 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 149 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 151 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 152 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 153 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 154 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 155 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 156 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 157 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 158 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 159 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 160 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 161 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 162 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 163 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 164 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 165 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 166 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 167 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 168 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 169 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 171 "tokenizer.l"
{ /* nothing */ }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 173 "tokenizer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1668 "lex.linguist_yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(c_comment):
case YY_STATE_EOF(xml_comment):
case YY_STATE_EOF(haskell_comment):
case YY_STATE_EOF(ocaml_comment):
case YY_STATE_EOF(python_dcomment):
case YY_STATE_EOF(python_scomment):
case YY_STATE_EOF(roff_comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 255 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 255 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 254);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{

	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;

    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;

    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );

    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );

    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 173 "tokenizer.l"
