/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JniLayer */

#ifndef _Included_jni_JniLayer
#define _Included_jni_JniLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JniLayer
 * Method:    jni_layer_initialize
 * Signature: ([II)J
 */
JNIEXPORT jlong JNICALL Java_jni_JniLayer_jni_1layer_1initialize
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     jni_JniLayer
 * Method:    jni_layer_mainloop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jni_JniLayer_jni_1layer_1mainloop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jni_JniLayer
 * Method:    jni_layer_set_button
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_jni_JniLayer_jni_1layer_1set_1button
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     jni_JniLayer
 * Method:    jni_layer_set_analog
 * Signature: (JIIF)V
 */
JNIEXPORT void JNICALL Java_jni_JniLayer_jni_1layer_1set_1analog
  (JNIEnv *, jobject, jlong, jint, jint, jfloat);

/*
 * Class:     jni_JniLayer
 * Method:    jni_layer_report_analog_chg
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jni_JniLayer_jni_1layer_1report_1analog_1chg
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jni_JniLayer
 * Method:    jni_layer_kill
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jni_JniLayer_jni_1layer_1kill
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
