#version 430 core

layout (local_size_x = 128) in;

struct particle
{
    vec2 position;
    vec2 velocity;
};

layout(std430, binding = 0) buffer particles_block
{
    particle particles[];
};

uniform uint particle_count;
uniform float time_delta;

void main()
{
    uint index = gl_GlobalInvocationID.x;
    if (index >= particle_count)
    {
        return;
    }
    particles[index].position += particles[index].velocity * time_delta;
}
