# Code generated by protoc-gen-twirp_ruby 1.14.1, DO NOT EDIT.
require "twirp"
require_relative "service_pb.rb"

module Example
  module Haberdasher
    class HaberdasherService < ::Twirp::Service
      package "example.haberdasher"
      service "Haberdasher"
      rpc :MakeHat, Size, Hat, ruby_method: :make_hat
    end

    class HaberdasherClient < ::Twirp::Client
      client_for HaberdasherService
    end
  end
end
