#!/bin/sh
# shellcheck disable=SC2006,SC2021
set -e
. "${0%/*}/includes.sh"

# Print non-essential feedback
log()([ "$quiet" ] || printf '%s\n' "$@")

# Display a shortened help summary and bail with an error code
bad_invocation()(die --code=2 "$usage")


# Parse options
usage="${0##*/} [-q|--quiet] [--replace submodule] url"
unset replace quiet
while [ -n "$1" ]; do case $1 in

	# Print an unabridged usage summary, then exit
	-h|--help|-\?)
		cat <<-HELP
		Usage:
		    $usage

		Options:
		    -q, --quiet               Do not print output unless there's a failure.
		    -r, --replace SUBMODDULE  Replace an existing grammar submodule.

		Examples:
		    $0 https://github.com/Alhadis/language-roff
		    $0 --replace sublime-apl https://github.com/Alhadis/language-apl
		HELP
		exit ;;

	# Hide non-essential feedback
	-q | --quiet)
		quiet=1
		break ;;

	# Replace an existing submodule
	-r* | --replace | --replace=*)
		case $1 in
			-r|--replace) replace=$2; shift ;; # -r [module], --replace [module]
			-r*)          replace=${1#??}   ;; # -r[module]
			--replace=*)  replace=${1#*=}   ;; # --replace=[module]
		esac ;;

	# Double-dash: Terminate option parsing
	--)
		shift
		break ;;

	# Invalid option: abort
	--* | -?*)
		warn 'invalid option: "%s"' "${0##*/}" "$1" >&2
		bad_invocation ;;

	# Argument not prefixed with a dash
	*) break ;;

esac; shift
done


# Don't proceed any further if we don't have a URL
[ "$1" ] || bad_invocation


# Check upfront that executables we depend on are available
have docker git sed ruby bundle || \
	die 'See CONTRIBUTING.md for help on getting started: https://git.io/J0eqy'


# Make sure Docker's running
log 'Checking Docker is installed and running'
cmd 'docker ps >/dev/null'

# Make sure we're running from checkout directory
root=`git rev-parse --git-dir`
root="${root%/.git}"
# shellcheck disable=SC3013
if [ ! "$root" = .git ] && [ -d "$root" ] && ! [ . -ef "$root" ] >/dev/null 2>&1; then
	log "Switching directory to $root"
	cmd cd "$root"
fi

# Ensure the given URL is an HTTPS link
url=`script/normalise-url --protocol=https "$1"`

# Make sure it's not already registered
path="vendor/grammars/${url##*/}"
path="${path%.git}"
if [ -e "$path" ] && [ -z "$replace" ]; then
	warn "Submodule '$path' already exists. Did you forget the '--replace' option?"
	warn "Run '$0 --help' for invocation advice"
	exit 1
fi

# Remove the old submodule if we're `--replace`ing one
if [ "$replace" ]; then

	# Normalise submodule reference
	replace=`printf %s "$replace" \
		| tr '[A-Z]' '[a-z]' \
		| sed 's/^\(.*\/\)\{0,1\}vendor\///; s/^grammars\///'`
	replace=`git config --list \
		| grep -Fi -m1 "submodule.vendor/grammars/$replace.url=" \
		| sed 's/\.url=.*//; s/^submodule\.//' || :`
	[ "$replace" ] || \
		die "Submodule '$replace' does not exist. Aborting."

	log "Deregistering submodule: $replace"
	cmd 'git submodule deinit' "$replace"
	cmd 'git rm -rf' "$replace"
	cmd "script/grammar-compiler$VERBOPTS_PARSED_OPTS update -f >/dev/null 2>&1"
fi

log "Registering new submodule: $url"
cmd 'git submodule add -f' "$url" "$path"
cmd 'script/grammar-compiler add' "$path"

log 'Caching grammar license'
cmd 'bundle exec licensed cache -c vendor/licenses/config.yml'

log 'Updating grammar documentation in vendor/README.md'
cmd 'bundle exec rake samples >/dev/null 2>&1'
cmd 'script/sort-submodules'
cmd 'script/list-grammars'
