#!/bin/sh
set -e
. "${0%/*}/includes.sh"
cd_root

cmd 'rm -rf ./linguist-grammars'
cmd './script/grammar-compiler compile -o linguist-grammars || true'
cmd 'tar -zcvf linguist-grammars.tar.gz linguist-grammars'
