#!/bin/sh

set -ex
cd "$(dirname "$0")/.."

image=linguist-grammar-build

while test $# -gt 0
do
    case "$1" in
        --build)
            docker build -t $image tools/grammars/
            ;;
        --init-submodules)
            git submodule update --init -j 8
            ;;
        *) echo "unknown argument: $1"; exit 1
            ;;
    esac
    shift
done

mkdir -p grammars
exec docker run --rm \
    -u $(id -u $USER):$(id -g $USER) \
    -v $PWD:/src/linguist \
    -w /src/linguist -ti $image \
    grammar-compiler -linguist=/src/linguist -json=/src/linguist/grammars
