#!/bin/sh

set -e

# Fetch all commits/refs needed to run our tests.
git fetch origin master:master v2.0.0:v2.0.0 test/attributes:test/attributes test/master:test/master

# Replace SSH links to submodules by HTTPS links.
sed -i 's|git@github.com:|https://github.com/|' .gitmodules

# Fetch all grammars
git submodule init
git submodule sync --quiet
script/fast-submodule-update

# Install dependent gems
bundle install --jobs 4 --retry 3 --without debug
