[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "github.com/groob/plist"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "gopkg.in/cheggaaa/pb.v1"
  version = "1.0.18"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"
