.TH WUMP 6 
.SH NAME
wump \- the game of hunt-the-wumpus
.SH SYNOPSIS
.B /usr/games/wump
.SH DESCRIPTION
.I Wump
plays the game of `Hunt the Wumpus.'
A Wumpus is a creature that lives in a cave with several rooms
connected by tunnels.
You wander among the rooms, trying to
shoot the Wumpus with an arrow, meanwhile avoiding
being eaten by the Wumpus and falling
into
Bottomless Pits.
There are also Super Bats which are likely to pick you up
and drop you in some random room.
.PP
The program asks various questions which you answer
one per line;
it will give a more detailed description
if you want.
.PP
This program is based on one described in
.I "People's Computer Company,"
.I 2,
2 (November 1973).
.SH BUGS
It will never replace Space War.
